# Generated by Django 3.1.4 on 2020-12-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
